
package tp.soacc.wsdl2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ElevePortType", targetNamespace = "http://soacc.tp")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ElevePortType {


    /**
     * 
     * @param bac
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:getMoyen")
    @WebResult(targetNamespace = "http://soacc.tp")
    @RequestWrapper(localName = "getMoyen", targetNamespace = "http://soacc.tp", className = "tp.soacc.GetMoyen")
    @ResponseWrapper(localName = "getMoyenResponse", targetNamespace = "http://soacc.tp", className = "tp.soacc.GetMoyenResponse")
    public int getMoyen(
        @WebParam(name = "bac", targetNamespace = "http://soacc.tp")
        String bac);

}
